name: Playwright Tests

on:
  workflow_dispatch:

env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  AGE: ${{ vars.AGE }}
  NAME: ${{ vars.NAME }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Use variables
      run: |
        echo "repository variable : $SAUCE_USERNAME"
        echo "organization variable : $SAUCE_ACCESS_KEY"
        echo "overridden variable : $AGE"
        echo "variable from shell environment : $NAME"
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test --project=chromium
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        AGE: ${{ vars.AGE }}
        NAME: ${{ vars.NAME }}
      
