name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run this workflow on'
        required: false
        default: 'feat/push-event'

env:
  GITHUB_TOKEN: ${{ github.token }}


jobs:
  test:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run saucectl
        uses: saucelabs/saucectl-run-action@v4
        with:
          working-directory: ./
          sauce-username: ${{ secrets.SAUCE_USERNAME }}
          sauce-access-key: ${{ secrets.SAUCE_ACCESS_KEY }}
          env: |
            AGE=${{ vars.AGE }}
            NAME_VALUE=${{ vars.NAME_VALUE }}


