name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  SAUCE_USERNAME: SAUCE_USERNAME
  SAUCE_ACCESS_KEY: SAUCE_ACCESS_KEY

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: apt update && apt install libfontconfig1 libenchant-2-2 libicu66 libevent-2.1-7 && npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test --project=chromium
